package com.redsamurai.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 08 20:14:38 EET 2018
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    void findInCache();
}

