package com.redsamurai.model.views;

import com.redsamurai.model.views.common.EmployeesView;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 08 20:13:39 EET 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl implements EmployeesView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }
    
    public void findInCache() {
        Key key = new Key(new Object[] { 100 });
        Row[] rows = this.findInCacheByKey(key, 1);
        System.out.println("Key = 100: " + rows.length);
        
        key = new Key(new Object[] { 130 });
        rows = this.findInCacheByKey(key, 1);
        System.out.println("Key = 130: " + rows.length);
    }
}

